os: Visual Studio 2017

platform:
  - x86
  - x64

init:
  - ps: Set-ExecutionPolicy RemoteSigned -scope CurrentUser
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - scoop install cmake
  - scoop install ninja

before_build:
  - mkdir build
  - cd build
  - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=RELEASE

build_script:
  - ninja
